name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Install dependencies
        run: go mod tidy
      - name: Test
        run: go test -v ./...
      - name: Run
        run: (cd simple-event-runner && go run cmd/main.go)
